[package]
name = "json-model"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "3"

[dependencies]
moirai-protocol = { git = "https://github.com/CEA-LIST/Moirai.git", "tag" = "v0.8" }
moirai-crdt = { git = "https://github.com/CEA-LIST/Moirai.git", "tag" = "v0.8" }
moirai-macros = { git = "https://github.com/CEA-LIST/Moirai.git", "tag" = "v0.8" }
moirai-fuzz = { git = "https://github.com/CEA-LIST/Moirai.git", "tag" = "v0.8" }
petgraph = "0.8.3"
rustc-hash = "1.1.0"
arachne-xmi = { path = "runtime/arachne-xmi" }
deepsize = { git = "https://github.com/leo-olivier/deepsize.git", optional = true, features = [
    "elsa",
] }
rand = "0.10.3"

[features]
default = ["fuzz", "sink"]
fuzz = ["moirai-crdt/fuzz", "moirai-macros/fuzz", "test_utils"]
sink = ["moirai-protocol/sink", "moirai-macros/sink", "moirai-crdt/sink"]
test_utils = [
    "dep:deepsize",
    "moirai-protocol/test_utils",
    "moirai-macros/test_utils",
    "moirai-crdt/test_utils",
]
