[package]
name = "json"
version = "0.1.0"
edition = "2024"

[dependencies]
moirai-protocol = { git = "https://github.com/CEA-LIST/Moirai.git", tag = "v0.6" }
moirai-fuzz = { git = "https://github.com/CEA-LIST/Moirai.git", tag = "v0.6" }
moirai-crdt = { git = "https://github.com/CEA-LIST/Moirai.git", tag = "v0.6" }
moirai-macros = { git = "https://github.com/CEA-LIST/Moirai.git", tag = "v0.6" }
petgraph = "0.8.3"
rand = "0.10.0"
xml-builder = "0.6.0"
deepsize = { git = "https://github.com/leo-olivier/deepsize.git", optional = true, features = ["elsa"] }

[features]
default = ["fuzz", "sink"]
fuzz = []
sink = ["moirai-protocol/sink","moirai-fuzz/sink","moirai-macros/sink","moirai-crdt/sink"]
test_utils = ["dep:deepsize","moirai-protocol/test_utils","moirai-macros/test_utils","moirai-crdt/test_utils"]
