<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="json" nsURI="http://www.example.org/json" nsPrefix="json">
    <eClassifiers xsi:type="ecore:EClass" name="Json" abstract="true" />
    <eClassifiers xsi:type="ecore:EClass" name="Array" eSuperTypes="#//Json">
        <eAnnotations source="urn:arachne:representation">
            <details key="kind" value="transparent"/>
            <details key="field" value="items"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1" eType="#//Json" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Object" eSuperTypes="#//Json">
        <eAnnotations source="urn:arachne:representation">
            <details key="kind" value="transparent"/>
            <details key="field" value="entry"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="entry" upperBound="-1" eType="#//Entry" containment="true">
            <eAnnotations source="urn:arachne:semantics">
                <details key="datatype" value="uw-map"/>
                <details key="key-feature" value="key"/>
                <details key="value-feature" value="value"/>
            </eAnnotations>
        </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="String" eSuperTypes="#//Json">
        <eAnnotations source="urn:arachne:representation">
            <details key="kind" value="transparent"/>
            <details key="field" value="value"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Number" eSuperTypes="#//Json">
        <eAnnotations source="urn:arachne:representation">
            <details key="kind" value="transparent"/>
            <details key="field" value="value"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Boolean" eSuperTypes="#//Json">
        <eAnnotations source="urn:arachne:representation">
            <details key="kind" value="transparent"/>
            <details key="field" value="value"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Entry">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" />
        <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//Json" containment="true" />
    </eClassifiers>
</ecore:EPackage>
